{{- if .Values.node.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fsx-csi-node
  labels:
    app.kubernetes.io/name: fsx-csi-node
spec:
  selector:
    matchLabels:
      app: fsx-csi-node
      {{- include "aws-fsx-csi-driver.labels" . | nindent 6 }}
{{ toYaml .Values.node.podDisruptionBudget | indent 2 }}
{{- end }}
